[2022-08-17 19:00:03,373] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:59:59.621950+00:00 [queued]>
[2022-08-17 19:00:03,547] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:59:59.621950+00:00 [queued]>
[2022-08-17 19:00:03,547] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:00:03,547] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 19:00:03,548] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:00:03,566] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 18:59:59.621950+00:00
[2022-08-17 19:00:03,574] {standard_task_runner.py:52} INFO - Started process 402 to run task
[2022-08-17 19:00:03,577] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T18:59:59.621950+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpyws3lp3t', '--error-file', '/tmp/tmpodr84ob9']
[2022-08-17 19:00:03,578] {standard_task_runner.py:80} INFO - Job 47: Subtask validate
[2022-08-17 19:00:03,644] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T18:59:59.621950+00:00 [running]> on host d254c144b912
[2022-08-17 19:00:03,730] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T18:59:59.621950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T18:59:59.621950+00:00
[2022-08-17 19:00:11,289] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:00:11,289] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 637ms/step
[2022-08-17 19:00:11,896] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:00:11,896] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 475ms/step
[2022-08-17 19:00:14,210] {logging_mixin.py:115} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials d66-20020a1f9b45000000b003791113188csm11028541vke.55 - gsmtp')
[2022-08-17 19:00:14,211] {logging_mixin.py:115} INFO - NOT VERIFIED:  [('jennifer aniston', 'ja@mail.com')]
[2022-08-17 19:00:14,211] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 19:00:14,271] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T185959, start_date=20220817T190003, end_date=20220817T190014
[2022-08-17 19:00:14,492] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 19:00:14,522] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
