[2022-08-17 19:49:24,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:44:07.158458+00:00 [queued]>
[2022-08-17 19:49:25,052] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:44:07.158458+00:00 [queued]>
[2022-08-17 19:49:25,052] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:49:25,053] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-17 19:49:25,053] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:49:25,069] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 19:44:07.158458+00:00
[2022-08-17 19:49:25,076] {standard_task_runner.py:52} INFO - Started process 2935 to run task
[2022-08-17 19:49:25,080] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T19:44:07.158458+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmprd3o88ss', '--error-file', '/tmp/tmp5jxhqr2c']
[2022-08-17 19:49:25,082] {standard_task_runner.py:80} INFO - Job 56: Subtask validate
[2022-08-17 19:49:25,143] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T19:44:07.158458+00:00 [running]> on host d254c144b912
[2022-08-17 19:49:25,269] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:44:07.158458+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:44:07.158458+00:00
[2022-08-17 19:49:31,766] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:49:31,766] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 472ms/step
[2022-08-17 19:49:32,053] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:49:32,054] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 203ms/step
[2022-08-17 19:49:35,108] {logging_mixin.py:115} INFO - Email sent successfully!
[2022-08-17 19:49:35,108] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 19:49:35,128] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T194407, start_date=20220817T194924, end_date=20220817T194935
[2022-08-17 19:49:35,212] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-17 19:49:35,214] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 2935. PIDs of all processes in the group: [2935]
[2022-08-17 19:49:35,214] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 2935
[2022-08-17 19:49:35,270] {process_utils.py:75} INFO - Process psutil.Process(pid=2935, status='terminated', exitcode=0, started='19:49:25') (2935) terminated with exit code 0
