[2022-08-17 18:41:23,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:41:18.892937+00:00 [queued]>
[2022-08-17 18:41:23,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:41:18.892937+00:00 [queued]>
[2022-08-17 18:41:23,291] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:41:23,291] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 18:41:23,291] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:41:23,313] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 18:41:18.892937+00:00
[2022-08-17 18:41:23,323] {standard_task_runner.py:52} INFO - Started process 422 to run task
[2022-08-17 18:41:23,328] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T18:41:18.892937+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpfgsm47i5', '--error-file', '/tmp/tmp8bi0tazy']
[2022-08-17 18:41:23,330] {standard_task_runner.py:80} INFO - Job 42: Subtask validate
[2022-08-17 18:41:23,422] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T18:41:18.892937+00:00 [running]> on host d254c144b912
[2022-08-17 18:41:23,545] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T18:41:18.892937+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T18:41:18.892937+00:00
[2022-08-17 18:41:31,179] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:41:31,179] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 663ms/step
[2022-08-17 18:41:31,709] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:41:31,710] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 407ms/step
[2022-08-17 18:41:34,223] {logging_mixin.py:115} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials y4-20020a1f3204000000b0035e9087e684sm10904169vky.24 - gsmtp')
[2022-08-17 18:41:34,223] {logging_mixin.py:115} INFO - NOT VERIFIED:  [('jennifer aniston', 'ja@mail.com')]
[2022-08-17 18:41:34,224] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 18:41:34,252] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T184118, start_date=20220817T184123, end_date=20220817T184134
[2022-08-17 18:41:34,433] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 18:41:34,496] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
