[2022-08-17 19:51:27,545] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:46:09.738768+00:00 [queued]>
[2022-08-17 19:51:27,769] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:46:09.738768+00:00 [queued]>
[2022-08-17 19:51:27,769] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:51:27,769] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-17 19:51:27,769] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:51:27,791] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 19:46:09.738768+00:00
[2022-08-17 19:51:27,800] {standard_task_runner.py:52} INFO - Started process 3102 to run task
[2022-08-17 19:51:27,812] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T19:46:09.738768+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmp2vsrhnwn', '--error-file', '/tmp/tmp7bf2hulz']
[2022-08-17 19:51:27,814] {standard_task_runner.py:80} INFO - Job 58: Subtask validate
[2022-08-17 19:51:27,893] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T19:46:09.738768+00:00 [running]> on host d254c144b912
[2022-08-17 19:51:27,981] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:46:09.738768+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:46:09.738768+00:00
[2022-08-17 19:51:34,630] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:51:34,630] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 468ms/step
[2022-08-17 19:51:34,937] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:51:34,937] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 230ms/step
[2022-08-17 19:51:37,886] {logging_mixin.py:115} INFO - Email sent successfully!
[2022-08-17 19:51:37,887] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 19:51:37,912] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T194609, start_date=20220817T195127, end_date=20220817T195137
[2022-08-17 19:51:37,952] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-17 19:51:37,954] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3102. PIDs of all processes in the group: [3102]
[2022-08-17 19:51:37,954] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3102
[2022-08-17 19:51:38,006] {process_utils.py:75} INFO - Process psutil.Process(pid=3102, status='terminated', exitcode=0, started='19:51:27') (3102) terminated with exit code 0
