[2022-08-17 18:53:48,336] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:53:43.901699+00:00 [queued]>
[2022-08-17 18:53:48,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:53:43.901699+00:00 [queued]>
[2022-08-17 18:53:48,528] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:53:48,529] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 18:53:48,529] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:53:48,548] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 18:53:43.901699+00:00
[2022-08-17 18:53:48,556] {standard_task_runner.py:52} INFO - Started process 96 to run task
[2022-08-17 18:53:48,559] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T18:53:43.901699+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpr0auejwu', '--error-file', '/tmp/tmpha5_sxkz']
[2022-08-17 18:53:48,560] {standard_task_runner.py:80} INFO - Job 46: Subtask validate
[2022-08-17 18:53:48,619] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T18:53:43.901699+00:00 [running]> on host d254c144b912
[2022-08-17 18:53:48,706] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T18:53:43.901699+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T18:53:43.901699+00:00
[2022-08-17 18:53:58,567] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:53:58,567] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 970ms/step
[2022-08-17 18:53:59,196] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:53:59,196] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 427ms/step
[2022-08-17 18:54:01,705] {logging_mixin.py:115} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v11-20020a056102330b00b0036692eb8ac7sm8495046vsc.14 - gsmtp')
[2022-08-17 18:54:01,706] {logging_mixin.py:115} INFO - NOT VERIFIED:  [('jennifer aniston', 'ja@mail.com')]
[2022-08-17 18:54:01,706] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 18:54:01,743] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T185343, start_date=20220817T185348, end_date=20220817T185401
[2022-08-17 18:54:01,928] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 18:54:02,030] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
